export const GET_TWEETS_START = 'GET_TWEETS_START';
export const GET_TWEETS_FINISH = 'GET_TWEETS_FINISH';

export const GET_TWEET_START = 'GET_TWEET_START';
export const GET_TWEET_FINISH = 'GET_TWEET_FINISH';

export const SET_TWEETS_FILTERS = 'SET_TWEETS_FILTERS';

export const SHOW_FETCH_MODAL = 'SHOW_FETCH_MODAL';
export const HIDE_FETCH_MODAL = 'HIDE_FETCH_MODAL';

export const REQUEST_FOR_FETCH_START = 'REQUEST_FOR_FETCH_START';
export const REQUEST_FOR_FETCH_FINISH = 'REQUEST_FOR_FETCH_FINISH';