export const GET_TWEETS_START = 'GET_TWEETS_START';
export const GET_TWEETS_FINISH = 'GET_TWEETS_FINISH';

export const GET_TWEET_START = 'GET_TWEET_START';
export const GET_TWEET_FINISH = 'GET_TWEET_FINISH';

export const SET_TWEETS_FILTERS = 'SET_TWEETS_FILTERS';